/**
 * 区域层 · 出厂区域预设数据 —— gui 桶 / chat 区域（刀2 / #223）。
 *
 * ★ **本文件是出厂区域预设的落盘数据（刀2 / #223 产出）；生成脚本已于刀3 删除——本文件即真值本体，手改即生效（#488 批⑥）。**
 *   它是**唯一真值**：10 套出厂预设的有效值由它算出（`effectivePresetTheme`）——
 *   改这里的任何一个值，等于改掉所有引用它的预设。历史来源见 `.agents/records/issue-223-factory-zone-presets-as-data.md`。
 * 值 = 生成时刻的 `pickZoneFields(GLOBAL_PRESETS[来源].theme, 'chat')`，逐字段照抄
 * （含终端补全烘入的默认值；cc 区含 ccLayout/ccHidden 两个元件名单字段）。
 */
import type { ZonePresetEntry } from '../zonePresetPool.ts'

export const FACTORY_GUI_CHAT: readonly ZonePresetEntry[] = [
  {
    id: 'glass',
    mode: 'gui',
    zone: 'chat',
    label: 'Glass Light',
    origin: 'factory',
    source: { presetName: 'glass' },
    values: {
      chatBg: "rgba(255,255,255,0.28)",
      chatFont: "system",
      chatFontSize: 15,
      chatLineHeight: 1.65,
      chatTextColor: "rgba(0,0,0,0.82)",
      chatCodeColor: "#7c3aed",
      chatCodeBg: "rgba(124,58,237,0.06)",
      synKeyword: "#7c3aed",
      synString: "#15803d",
      synComment: "rgba(0,0,0,0.45)",
      synLiteral: "#b45309",
      synEntity: "#0f766e",
      synFunction: "#1d4ed8",
      synVariable: "rgba(0,0,0,0.82)",
      synProperty: "rgba(0,0,0,0.82)",
      synRegex: "#b45309",
      synMarkupHeading: "#7c3aed",
      synSupport: "#1d4ed8",
      toolOk: "#22c55e",
      toolRun: "#6366f1",
      toolErr: "#f43f5e",
      userTagBg: "rgba(99,102,241,0.08)",
      diffAdded: "#22c55e",
      diffRemoved: "#f43f5e",
      diffAddedWord: "#16a34a",
      diffRemovedWord: "#e11d48",
      toolIndicatorGlow: 2,
      toolConnectorMode: "follow",
      spinnerFramePreset: "clock",
      spinnerStalledColor: "#ef4444",
      spinnerColor: "#f59e0b",
      msgFont: "system",
      msgLineHeight: 1.75,
    },
  },
  {
    id: 'solarized',
    mode: 'gui',
    zone: 'chat',
    label: 'Solarized Light',
    origin: 'factory',
    source: { presetName: 'solarized' },
    values: {
      chatBg: "#fdf6e3",
      chatBgImage: "",
      chatTransparency: 1,
      chatBlur: 0,
      chatFont: "mono",
      chatFontSize: 15,
      chatLineHeight: 1.6,
      chatTextColor: "#657b83",
      chatCodeColor: "#b58900",
      chatCodeBg: "rgba(38,139,210,.06)",
      synKeyword: "#859900",
      synString: "#2aa198",
      synComment: "#93a1a1",
      synLiteral: "#d33682",
      synEntity: "#268bd2",
      synFunction: "#268bd2",
      synVariable: "#657b83",
      synProperty: "#657b83",
      synRegex: "#d33682",
      synMarkupHeading: "#268bd2",
      synCoReference: "#65737e",
      synSupport: "#6c71c4",
      toolOk: "#859900",
      toolRun: "#268bd2",
      toolErr: "#dc322f",
      userTagBg: "#eee8d5",
      diffAdded: "#859900",
      diffRemoved: "#dc322f",
      diffAddedWord: "#859900",
      diffRemovedWord: "#dc322f",
      editorFontSize: 13,
      editorLineHeight: 1.5,
      editorGutterColor: "#93a1a1",
      editorGutterBg: "transparent",
      editorSelection: "rgba(38,139,210,0.18)",
      editorActiveLine: "rgba(88,110,117,0.06)",
      editorTabActive: "#268bd2",
      editorModifiedMark: "#b58900",
      toolIndicator: "●",
      toolIndicatorRun: "circle",
      toolIndicatorOk: "check",
      toolIndicatorErr: "cross",
      toolIndicatorGlow: 0,
      toolIndicatorGlowColor: "",
      toolConnectorMode: "none",
      toolConnectorColor: "#93a1a1",
      toolConnectorStyle: "solid",
      toolConnectorWidth: 2,
      toolConnectorOpacity: 1,
      spinnerFramePreset: "wave",
      spinnerCustomFrames: "",
      spinnerVerbSet: "zh",
      spinnerCustomVerbs: "",
      spinnerStalledColor: "#dc322f",
      spinnerDoneMarker: "✓",
      spinnerCancelledMarker: "■",
      spinnerErrorMarker: "!",
      spinnerDoneMarkerMode: "custom",
      spinnerCancelledMarkerMode: "custom",
      spinnerErrorMarkerMode: "custom",
      spinnerIntervalMs: 120,
      spinnerColor: "#b58900",
      spinnerSize: 14,
      msgStyle: "terminal",
      msgFont: "mono",
      msgTextColor: "#657b83",
      msgLineHeight: 1.6,
      messageLayout: "classic",
      messageUserBg: "",
      messageAssistantBg: "",
      messageReasoningBg: "",
      messageBorderColor: "",
      messageRadius: 0,
      assistantDot: false,
      assistantDotGlyph: "●",
      assistantDotColor: "#268bd2",
      assistantDotImage: "",
    },
  },
  {
    id: 'agent-command',
    mode: 'gui',
    zone: 'chat',
    label: 'Agent 指挥台',
    origin: 'factory',
    source: { presetName: 'agent-command' },
    values: {
      chatBg: "#08111f",
      chatTextColor: "#dbeafe",
      chatCodeColor: "#7dd3fc",
      chatCodeBg: "rgba(56,189,248,0.07)",
      toolOk: "#4ade80",
      toolRun: "#38bdf8",
      toolErr: "#fb7185",
      userTagBg: "rgba(56,189,248,0.12)",
      diffAdded: "#4ade80",
      diffRemoved: "#fb7185",
      diffAddedWord: "#86efac",
      diffRemovedWord: "#fda4af",
      toolConnectorColor: "#294764",
      spinnerColor: "#38bdf8",
      msgLineHeight: 1.62,
      messageLayout: "bubble",
    },
  },
  {
    id: 'agent-map',
    mode: 'gui',
    zone: 'chat',
    label: 'Agent 关系图',
    origin: 'factory',
    source: { presetName: 'agent-map' },
    values: {
      chatBg: "#11101d",
      chatTextColor: "#ede9fe",
      chatCodeColor: "#c4b5fd",
      chatCodeBg: "rgba(167,139,250,0.08)",
      toolOk: "#5eead4",
      toolRun: "#a78bfa",
      toolErr: "#fb7185",
      userTagBg: "rgba(167,139,250,0.13)",
      diffAdded: "#5eead4",
      diffRemoved: "#fb7185",
      diffAddedWord: "#99f6e4",
      diffRemovedWord: "#fda4af",
      toolConnectorColor: "#494064",
      spinnerColor: "#a78bfa",
      msgLineHeight: 1.68,
      messageLayout: "bubble",
    },
  },
  {
    id: 'focus-flow',
    mode: 'gui',
    zone: 'chat',
    label: '专注流程',
    origin: 'factory',
    source: { presetName: 'focus-flow' },
    values: {
      chatBg: "#181713",
      chatTextColor: "#e7e0d5",
      chatCodeColor: "#dfbd83",
      chatCodeBg: "rgba(214,168,95,0.06)",
      toolOk: "#a3b18a",
      toolRun: "#d6a85f",
      toolErr: "#cf7b73",
      userTagBg: "rgba(214,168,95,0.10)",
      diffAdded: "#a3b18a",
      diffRemoved: "#cf7b73",
      diffAddedWord: "#c3ceb2",
      diffRemovedWord: "#e3aaa4",
      toolConnectorColor: "#4b463d",
      spinnerColor: "#d6a85f",
      msgLineHeight: 1.72,
      messageLayout: "claude",
    },
  },
]

// 本文件 5 条 / 163 个字段值
